# Tensors 

In [2]:
import torch

## zeros()

In [3]:
w=torch.zeros(4,3)
w

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

## size() and shape

In [4]:
w.size()

torch.Size([4, 3])

In [5]:
w.shape

torch.Size([4, 3])

## randn() and randn_like()

In [7]:
w=torch.randn(4,3)
w

tensor([[-2.3306,  1.6464, -0.2680],
        [-0.1275, -2.5210,  0.5209],
        [-1.0454, -0.7630,  0.6096],
        [-0.1503,  0.9528,  1.2927]])

In [8]:
t=torch.randn_like(w)
t

tensor([[ 0.5370, -0.9246, -0.4325],
        [ 0.0167, -1.1255,  0.5449],
        [-0.2213,  0.1926,  0.5575],
        [ 0.2986, -1.9777,  0.3260]])

## fill_()

In [9]:
w.fill_(1)
w

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

## view()

In [11]:
t=w.view(6,2)
t

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])

In [12]:
tt=w.view(3,-1)
tt

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

## numpy()

In [13]:
w.numpy()

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [14]:
type(w)

torch.Tensor

In [15]:
type(w.numpy())

numpy.ndarray