In [25]:
# Babak Poursartip
# April 17, 2022
# Vectors
# Always define the exact size of the vectors to prevent any misinterpretations.


In [26]:

import numpy as np

a = np.random.randn(5)
print(a)

[ 1.10485869 -1.64029534 -0.46879509 -0.04053446  0.97187866]


In [27]:
print(a.shape)  # This is a rank 1 array.

(5,)


In [28]:
print(a.T)

[ 1.10485869 -1.64029534 -0.46879509 -0.04053446  0.97187866]


In [29]:
print(a.T.shape)

(5,)


In [30]:
print(np.dot(a, a.T))

5.077241535725279


In [32]:
b = np.random.randn(5,1)
print(b)

[[-1.38553719]
 [ 0.57275793]
 [-1.68090471]
 [-0.02422916]
 [ 0.83415554]]


In [33]:
print(b.T)

[[-1.38553719  0.57275793 -1.68090471 -0.02422916  0.83415554]]


In [34]:
print(np.dot(b,b.T))

[[ 1.91971330e+00 -7.93577412e-01  2.32895599e+00  3.35703963e-02
  -1.15575352e+00]
 [-7.93577412e-01  3.28051647e-01 -9.62751506e-01 -1.38774411e-02
   4.77769202e-01]
 [ 2.32895599e+00 -9.62751506e-01  2.82544066e+00  4.07269021e-02
  -1.40213598e+00]
 [ 3.35703963e-02 -1.38774411e-02  4.07269021e-02  5.87051988e-04
  -2.02108845e-02]
 [-1.15575352e+00  4.77769202e-01 -1.40213598e+00 -2.02108845e-02
   6.95815467e-01]]


In [36]:
assert(b.shape==(5,1))